name: Testing and Deploy simulating
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code 
        uses: actions/checkout@v4
      - name: install packs
        run: npm ci
      - name: lint and test
        run: | 
          npm run lint
          npm run test
      - name: build project
        run: npm run build
      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr --delete --exclude="" --include="" --filter=""
          path: dist/
          remote_path: /var/www/cicd.devdata.uz/public_html/
          remote_host: devdata.uz
          remote_user: dev
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      # - name: Connecting to the server
      #   run: ssh -vvv dev@139.162.181.22
      # - name: Deploy with rsync
      #   run: rsync -rt ./dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/cicd.devdata.uz/public_html/